### ISSUE TITLE
Problem of importation for the FoscamAPI

### ISSUE THREAD

**Issue by MartinPolytech** [hypothermic/FoscamAPI#1]
Hello !
I'm trying to import this library on Eclipse or IntelliJ but it's not working. IntelliJ or Eclipse don't find the dependency.
Do you have any clue for beginners ?

**Comment by hypothermic** [comment]
Hello.

I recommend creating a Gradle or Maven project for easy dependency management.
Eclipse and IntelliJ have both of these built-in, as far as I know.

Here's a step-by-step guide on setting up a Gradle project in IntelliJ:
1. `File -> New -> Project... ` and select `Gradle` from the left list
In IntelliJ it's `File -> New -> Project...` and select `Gradle` from the left list. Click "Next" and subsequently click "Finish". Wait for it to generate your project.
2. Open the `build.gradle` file in your newly created project and change the "repositories" and "dependency" properties to the following:
```groovy
repositories {
    maven {
        url "https://raw.github.com/hypothermic/foscamapi/mvn-repo/"
    }
}

dependencies {
    compile group: 'nl.hypothermic', name: 'foscamlib', version: '1.08-RELEASE'
}
```

Now you should be able to use this library in your code.

I'm happy to help if you have any further questions

**Comment by MartinPolytech** [comment]
First of all thanks a lot for the anwser. 

I still got some issue, and I can't find if this is because of the importation of the library or if my Java code is wrong. 

May you check it please, sorry for asking that but I don't know who to ask.

![FoscamAPI](https://user-images.githubusercontent.com/61868659/76241921-0fbcaa00-6236-11ea-8126-ea842a290b21.PNG)

Have a good evening

**Comment by hypothermic** [comment]
As far as I can see on the screenshot, you've imported the library correctly.

The error is actually caused because you don't handle the `ConnectException` which can be thrown when creating a new `Foscam` object.
&nbsp;

Replace the camera method with:
```java
public void camera(String IP, int port, String name, String mdp) {
    try {
        Foscam camera = new Foscam("...", 88, "...", "...");
    } catch (Exception e) {
        e.printStackTrace(); // TODO handle the error
    }
}
```
or, alternatively,
```java
public void camera(String IP, int port, String name, String mdp) throws Exception {
    Foscam camera = new Foscam("...", 88, "...", "...");
}
```

If that doesn't work, could you upload the code or create a repository for it? Remove any sensitive information beforehand.
&nbsp;

If you have any more questions I'd be happy to help.
It's hard to learn Java, especially if it's just a hobby :)

Have a good evening too.

**Comment by MartinPolytech** [comment]
Hello, 

We still have a few problems with our project. We decided to switch to Maven. We can import the library but we have a problem with the java compiler version. When we try to build the project this appears : 

![image](https://user-images.githubusercontent.com/61868659/76535365-083a1280-647b-11ea-9f4c-94d9b19f34f9.png)

Thanks again for your help 

Have a good day :)

**Comment by hypothermic** [comment]
I haven't used Eclipse since 2014, so excuse me if I'm wrong.

1. You need to tell Eclipse which JDK to use for the project. Here is [a useful guide](https://www.baeldung.com/eclipse-change-java-version) and [a wiki page](https://wiki.eclipse.org/Java13/Examples) on the topic.
2. You need to tell Maven which compiler to use. Specify it in your `pom.xml`:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.8.1</version>
	<configuration>
		<source>13</source>
		<target>13</target>
                <release>13</release>
		<compilerArgs>
		        --enable-preview
		</compilerArgs>
	</configuration>
</plugin>
```

Hope this helps!

**Comment by hypothermic** [comment]
Hello.
Has the issue been resolved?
If yes, I'll close this ticket.

**Comment by MartinPolytech** [comment]
Hello ! Thanks a lot for your help, it's working, I have an other problem but this is different as a problem of importation. I'm sorry for the delay, since the Coronavirus issue, I couldn't work on my project . You've been a great help for me !
